version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - CADDY_ADMIN_API=http://host.docker.internal:2019
      - STREAMLIT_SERVER_PORT=5000
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=true
    restart: unless-stopped

