services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./data/db:/app/instance  # Persistent SQLite storage
      - ./data/configs:/app/configs    # Caddy config backups
      - ./debug_files:/app/debug
    restart: unless-stopped

